visual_math/apps/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.register, name='register'),  # Страница регистрации
    path('home/', views.home, name='home'),
    path('delete/', views.delete_user, name='delete_user'),
    path('logout/', views.logout_view, name='logout'),  # Путь для выхода
    path('delete-user/', views.delete_user_confirmed, name='delete_user_confirmed'),
    path('logout-user/', views.logout_confirmed, name='logout_confirmed'),
    # path('login/', views.login_view, name='login'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('update-password/', views.update_password, name='update_password'),
    path('password_reset/', views.reset_password, name='password_reset'),

    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visual_math/visual_math_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls')),  # Подключаем URL-ы для пользователей
    path('presentations/', include('apps.presentations.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visual_math/apps/presentations/models.py
from django.db import models
from django.contrib.auth.models import User  # Импортируем модель User, если используется авторизация
from django.conf import settings
from django.db.models import JSONField
import datetime

class Presentation(models.Model):
    SUBJECT_CHOICES = (
        ('Calculus', 'Математический анализ'),
        ('Algebra', 'Алгебра'),
        ('Discrete', 'Дискретная математика'),
    )
    title = models.CharField(max_length=255)
    subject = models.CharField(max_length=50, choices=SUBJECT_CHOICES, default='Calculus')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='presentations', default=37)
    created_at = models.DateTimeField(default=datetime.datetime.now)
    updated_at = models.DateTimeField(default=datetime.datetime.now)
    data = JSONField(default=dict)  # Сохраняет структуру JSON в базе данных
    #current_slide = models.PositiveIntegerField(default=0) #??
    is_active = models.BooleanField(default=False)
    def __str__(self):
        return self.title

class Slide(models.Model):
    presentation = models.ForeignKey(Presentation, on_delete=models.CASCADE, related_name='slides')
    slide_number = models.PositiveIntegerField(editable=False, default=0)
    slide_type = models.CharField(max_length=50,
                                  choices=[('text', 'Текстовый'), ('test', 'Проверочный'), ('questionnaire', 'Вопросник')],
                                  default='text')
    content = models.TextField(blank=True)
    questions = models.JSONField(default=list, blank=True)  # List of questions (text)
    image = models.ImageField(upload_to='slides/', null=True, blank=True)

    def __str__(self):
        return f"Слайд {self.slide_number} из '{self.presentation.title}'"

visual_math/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    ROLE_CHOICES = (
        ('student', 'Студент'),
        ('teacher', 'Преподаватель'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='student')
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.username

visual_math/apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'placeholder': 'Имя пользователя', 'class': 'form-control'}), # имя пользователя везде надо поменять на логин
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Пароль', 'class': 'form-control'}),
    )

class UpdateProfileForm(forms.ModelForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите новый email',
    }))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите новое имя пользователя',
    }))

    class Meta:
        model = User
        fields = ['username', 'email']

class UpdatePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Старый пароль'}),
    )
    new_password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Новый пароль'}),
    )
    new_password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтвердите новый пароль'}),
    )

class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='Введите ваш email')

visual_math/apps/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, update_session_auth_hash, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
from .forms import LoginForm
from django.contrib.auth.decorators import login_required
from .forms import UpdateProfileForm, UpdatePasswordForm, PasswordResetForm
from django.contrib import messages
import random
import string
from django.core.mail import send_mail
from .models import User

def register(request):
    reg_form = CustomUserCreationForm()
    log_form = LoginForm()
    if request.method == 'POST':
        if 'register' in request.POST:
            reg_form = CustomUserCreationForm(request.POST)
            if reg_form.is_valid():
                user = reg_form.save()
                user.role = 'student'
                login(request, user)  # Авторизуем пользователя сразу после регистрации
                return redirect('home')  # Перенаправляем на главную страницу
            else:
                reg_form.add_error(None, 'Неверные данные при регистрации')
        elif 'login' in request.POST:
            log_form = LoginForm(request.POST)
            if log_form.is_valid():
                username = log_form.cleaned_data['username']
                password = log_form.cleaned_data['password']
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('home')
                else:
                    log_form.add_error(None, 'Неправильное имя пользователя или пароль')
            else:
                log_form.add_error(None, 'Неверные данные при входе')

    return render(request, 'users/register.html', {
        'reg_form': reg_form,
        'log_form': log_form
    })

@login_required(login_url='/')
def home(request):
    presentations = request.user.presentations.all().order_by('-created_at')  # Сортируем по убыванию
    return render(request, 'users/home.html', {'user': request.user, 'presentations': presentations})


@login_required(login_url='/')
def delete_user(request):
    return render(request, 'users/delete_user.html')

@login_required(login_url='/')
def delete_user_confirmed(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
        logout(request)
        return redirect('register')  # Перенаправляем на главную страницу после удаления пользователя

    return render(request, 'users/delete_user.html')

@login_required(login_url='/')
def logout_view(request):
    return render(request, 'users/logout_user.html')

@login_required(login_url='/')
def logout_confirmed(request):
    logout(request)  # Выход из аккаунта
    return redirect('register')  # Перенаправляем на страницу регистрации


@login_required(login_url='/')
def update_profile(request):
    if request.method == 'POST':
        form = UpdateProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ваш профиль успешно обновлен!')
            return redirect('home')
    else:
        form = UpdateProfileForm(instance=request.user)

    return render(request, 'users/update_profile.html', {'form': form})

@login_required(login_url='/')
def update_password(request):
    if request.method == 'POST':
        form = UpdatePasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Чтобы пользователь не был разлогинен
            messages.success(request, 'Пароль успешно изменен!')
            return redirect('home')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки ниже.')
    else:
        form = UpdatePasswordForm(user=request.user)

    return render(request, 'users/update_password.html', {'form': form})


def generate_random_password(length=8):
    characters = string.ascii_letters + string.digits + string.punctuation
    return ''.join(random.choice(characters) for i in range(length))

# Представление для сброса пароля
def reset_password(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.filter(email=email).first()

            if user:
                new_password = generate_random_password()  # Генерируем новый случайный пароль
                user.set_password(new_password)  # Устанавливаем новый пароль
                user.save()

                # Отправляем email с новым паролем
                send_mail(
                    'Ваш новый пароль',
                    f'Ваш новый пароль: {new_password}',
                    'from@example.com',
                    [email],
                    fail_silently=False,
                )

                return redirect('register')
            else:
                # Если пользователь не найден
                return render(request, 'users/password_reset_form.html', {'form': form, 'error': 'Пользователь с таким email не найден.'})

    else:
        form = PasswordResetForm()

    return render(request, 'users/password_reset_form.html', {'form': form})

visual_math/apps/users/templates/users/delete_user.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     {% load static %}
    <link href="{% static 'css/delete_user.css' %}" rel="stylesheet">
    <title>Удалить учетную запись</title>
</head>
<body>
 <div class="container">
    <h2>Вы уверены, что хотите удалить свою учетную запись?</h2>
    <form action="{% url 'delete_user_confirmed' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
    <a href="{% url 'home' %}">Отменить</a>
 </div>
</body>
</html>

visual_math/apps/users/templates/users/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Главная страница</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- Подключаем CSS файл -->
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
    <link href="{% static 'css/show_slides_students.css' %}" rel="stylesheet">
    <link href="{% static 'css/show_slides.css' %}" rel="stylesheet">
    <link href="{% static 'css/instruction.css' %}" rel="stylesheet">
    <link href="{% static 'css/sidebar.css' %}" rel="stylesheet">
    <script src="{% static 'js/home.js' %}" defer></script>
    <script src="{% static 'js/student_slides.js' %}" defer></script>
    <script src="{% static 'js/show_slides.js' %}" defer></script>
    <script src="{% static 'js/show_slides_stats.js' %}" defer></script>
    <script src="{% static 'js/teacher_slides.js' %}" defer></script>
    <link rel="icon" type="image/x-icon" href="{% static 'images/icon.png' %}">
     <!-- KaTeX для формул -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"></script>
</head>
<body>

<header id="header">
    <h1>
        <span>Welcome</span>
        <span>to</span>
        <span>VisualMath</span>
    </h1>
</header>

<main>
    <!-- Боковая панель -->
    <article class="side-nav">
        <div id="resizer"></div>
    <!-- Панель информации об аккаунте -->
        <div id="sidebar" class="sidebar">
            <button class="close-btn" onclick="closeSidebar()">
                <img src="{% static 'images/close-sidebar.png' %}" alt="Закрыть">
            </button>
            <h3>Информация </br> об аккаунте</h3>
            <p><strong>Статус:</strong> {{ user.get_role_display }}</p>
            <p><strong>Имя пользователя:</strong> {{ user.username }}</p>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <a href="{% url 'register' %}">
                <button class="btn-logout">Выйти из аккаунта</button>
            </a>
            <button class="btn-values" onclick="showContent('change')">Изменить данные аккаунта</button>
            <a href="{% url 'delete_user' %}">
                <button class="btn-delete">Удалить аккаунт</button>
            </a>
        </div>
        <!-- Кнопка открытия панели -->
        <button id="account" class="open-btn" onclick="openSidebar()">☰ Аккаунт</button>
        {% if user.role == 'teacher' %}
        <!-- Навигация -->
            <button class="butt" onclick="showContent('library')">Библиотека лекций</button>
            <button class="butt" onclick="showContent('instruction')">Инструкция</button>
        {% endif %}
        {% if user.role == 'student' %}
            <button class="butt" onclick="showJoinForm()">Зайти на презентацию</button>
        {% endif %}

        <div id="join-form" class="hidden">
            <input type="text" id="presentation-id" placeholder="Введите ID презентации">
            <button onclick="joinPresentation({{ user.id }})">Зайти</button>
            <button onclick="closeJoinForm()">Закрыть</button>
        </div>
    </article>

    <!-- Основной контент -->
    <div class="content">
        <article class = "con">
            <h2 id="desc">Навигация по сайту</h2>
            <div class = "text">
                <h3>Аккаунт</h3>
                <ul>
                    <li><p>В этом разделе отображается основная информация о пользователе: статус (например, "Преподаватель"), имя пользователя, email и другие данные.</p></li>
                    <li><p>Предоставляется возможность редактировать данные аккаунта (например, изменить имя, email или пароль) или удалить акакунт.</p></li>
               </ul>
                {% if user.role == 'teacher' %}
                <h3>Библиотека лекций</h3>
                <ul>
                    <li><p>В этом разделе хранятся все созданные преподавателем лекции.</p></li>
                    <li><p>Возможна сортировка по названию лекции / по модулю лекции.</p></li>
                    <li><p>Возможны создание, показ и удаление лекций.</p></li>
               </ul>
               <h3>Инструкция</h3>
                <ul>
                    <li><p>Данный раздел содержит всю необходимую информацию для успешного создания и показа лекций.</p></li>
                    <li><p>При возникновении вопросов, ответы на которых не содержатся в инструкции, напишите на нашу почту.</p></li>
               </ul>
                {% endif %}
                {% if user.role == 'student' %}
                <h3>Зайти на презентацию</h3>
                <ul>
                    <li><p>Перейдя по этой ссылке вы можете попасть на показ презентации.</p></li>
                    <li><p>Чтобы зайти на нужную лекцию необходимо ввести id презентации.</p></li>
               </ul>
                {% endif %}
            </div>
            <h3 class="show-role">Ваша роль: <b class="role">{{ user.get_role_display }}</b></h3>
        </article>
        <div id="library-content" class="hidden">
            <section>
                <h2 id="section2">Библиотека лекций</h2>
                <div id="nav-presentation">
                    <button class = "close" onclick="closeModule()">Назад</button>
                    {% if user.role == 'teacher' %}
                        <a href = "/presentations/create/"><button class = "close" >Создать лекцию</button></a>
                    {% endif %}
                </div>
                <label for="subject">Выберите предмет:</label>
                <select id="subject" onchange="filterBySubject()">
                    <option value="">-- Выберите предмет --</option>
                    <option value="Calculus">Математический анализ</option>
                    <option value="Algebra">Алгебра</option>
                    <option value="Discrete">Дискретная математика</option>
                </select>

                <div id="presentations-container">
                    {% if presentations %}
                        {% for el in presentations %}
                            <div class="presentation-card" data-subject="{{ el.subject }}">
                                <h3>{{ el.title }}</h3>
                                <p><strong>Предмет:</strong> {{ el.get_subject_display }}</p>
                                <p><strong>Дата создания:</strong> {{ el.created_at|date:"d.m.Y H:i" }}</p>
                                <button onclick="openPresentation({{ el.id }})" class="presentation-button">Показать лекцию</button>
                                <button  onclick="deleteLecture({{ el.id }})"  class="link-button" >Удалить лекцию</button>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>У вас еще нет презентаций.</p>
                    {% endif %}
                </div>

                <div id="math-analysis" class="lecture-list" style="display: none;"></div>
                <div id="algebra" class="lecture-list" style="display: none;"></div>
                <div id="discrete-math" class="lecture-list" style="display: none;"></div>

            </section>
        </div>

    <div id="change-content" class="hidden">
        <h2>Изменение данных аккаунта</h2>
        <a href = "{% url 'update_profile' %}"><button class="btn">Изменить профиль аккаунта</button></a>
        <a href = "{% url 'update_password' %}"><button class="btn">Изменить пароль аккаунта</button></a>
        <button class = "close" onclick="closeModule()">Назад</button>
    </div>
    <div id="instruction-content" class="hidden">
            <h2>Инструкция для преподавателей</h2>
            <div class="instruction-text">
                <h3>Создание лекции</h3>
                <ol>
                    <li>Нажмите кнопку "Библиотека лекций" в боковом меню.</li>
                    <li>Нажмите кнопку "Создать лекцию".</li>
                    <li>Заполните необходимые поля: название, предмет.</li>
                    <li>Добавляйте/удаляйте/редактируйте слайды.</li>
                    <li>Нажмите кнопку "Сохранить презентацию".</li>
                </ol>
                <h3>Проведение лекции</h3>
                <ol>
                    <li>Нажмите кнопку "Библиотека лекций" в боковом меню.</li>
                    <li>Найдите нужную вам презентацию.</li>
                    <li>Нажмите "Показать лекцию".</li>
                    <li>Студенты смогут подключиться, введя ID презентации, который вы увидите перед началом показа.</li>
                    <li>Управляйте слайдами с помощью кнопок "Вперед" и "Назад".</li>
                </ol>
                <h3>Дополнительные возможности</h3>
                <ol>
                    <li>Сортировка лекций по предмету.</li>
                    <li>Удаление ненужных лекций.</li>
                    <li>Изменение почты/имени аккаунта.</li>
                     <li>Изменение пароля аккаунта.</li>
                </ol>
                <h3>Сохранение статистики в файл</h3>
                <p>Если у вас возникли проблемы с открытием csv файла в Excel (Windows):</p>
                <ul>
                    <li>Откройте Excel.</li>
                    <li>Вкладка "Данные" → "Получить данные" → "Из текста/CSV".</li>
                    <li>Выберите скачанный файл.</li>
                    <li>Установите кодировку: 65001: Юникод (UTF-8).</li>
                    <li>Нажмите "Загрузить".</li>
                </ul>
                <p class="highlighted-note">Если у вас возникли вопросы, пожалуйста, напишите нам на почту: visualmathproject2024@gmail.com</p>
            </div>
            <button class = "close" onclick="closeModule()">Назад</button>
        </div>
    </div>

</main>
<footer>
    <div class = "wrapper">
        <p class = "title">Контакты</p>
        <div class = "textwidget">
            <p><b>Почта:</b> visualmathproject2024@gmail.com </p>
        </div>
    </div>
</footer>
<div id="slide-show-container" class="hidden"></div>
<div id="student-slide-show" class="hidden">
    <button class="close-slide-btn" onclick="closeStudentPresentation()">Закрыть</button>
    <div id="student-slide-content"></div>
</div>
</body>
</html>

visual_math/apps/users/templates/users/logout_user.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Выйти из учетной записи</title>
</head>
<body>
    <h2>Вы уверены, что хотите выйти?</h2>
    <form action="{% url 'logout_confirmed' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Продолжить</button>
    </form>
    <a href="{% url 'home' %}">Отменить</a>
</body>
</html>

visual_math/apps/users/templates/users/password_reset_form.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вход в аккаунт</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h2>Сбросить пароль</h2>
        <p>Введите свой адрес электронной почты, и мы отправим вам ссылку для сброса пароля.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Сбросить пароль</button>
        </form>

        {% if error %}
            <p style="color: red;">{{ error }}</p>
        {% endif %}
    </div>
</body>
</html>

visual_math/apps/users/templates/users/register.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <!-- Подключение Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <!-- Подключение Animate.css -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet">
    <!-- Подключение кастомного CSS -->
    <link href="{% static 'css/register.css' %}" rel="stylesheet">
    <link href="{% static 'css/mobile_style_reg.css' %}" rel="stylesheet">
    <script src="{% static 'js/register.js' %}" defer></script>
    <link rel="icon" type="image/x-icon" href="{% static 'images/icon.png' %}">
</head>
<body>
<header>
    <h1>
    <span>Welcome</span>
    <span>to</span>
    <span>VisualMath</span>
    </h1>
</header>

<main>
    <article class="text">
        <section>
            <p id="introduction-text"></p>
            </br>
            <p id="footer"></p>
        </section>
    </article>

    <div class="container">
        <div class = "forms">
            <!-- Тело карточки -->
            <div style="display: flex; align-items: center; justify-content: center; font-size: 30px; font-family: 'Montserrat Medium', serif; font-weight: bold; width: 100%; ">
                Вход/Регистрация
            </div>
            <div class="login-box card-body">
                <!-- Форма входа -->
                <form method="POST" class="mt-4">
                    {% csrf_token %}
                    <!-- Поле для имени пользователя -->
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                        <input type="text" name="username"
                               class="form-control {{ log_form.username.errors|yesno:'is-invalid,' }}"
                               placeholder="Имя пользователя"
                               value="{{ log_form.username.value|default:'' }}">
                        {% if log_form.username.errors %}
                            <div class="invalid-feedback">
                                {{ log_form.username.errors|striptags }}
                            </div>
                        {% endif %}
                    </div>

                    <!-- Поле для пароля -->
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fas fa-lock"></i></span>
                        <input type="password" name="password"
                               class="form-control {{ log_form.password.errors|yesno:'is-invalid,' }}"
                               placeholder="Пароль"
                               value="{{ log_form.password.value|default:'' }}">
                        {% if log_form.password.errors %}
                            <div class="invalid-feedback">
                                {{ log_form.password.errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <!-- Кнопка отправки -->
                    <button type="submit" class="send reg" name="login">Войти</button>
                    <p style="text-align: right; margin-top: 10px;"><a href="{% url 'password_reset' %}" class="password-reset-link">Забыли пароль?</a></p>
                </form>
            </div>

            <div class="signup-box card-body">
                 <form method="POST">
                     {% csrf_token %}
                     <div class="input-group mb-3">
                         <span class="input-group-text"><i class="fas fa-user"></i></span>
                         <input type="text" name="username" class="form-control" placeholder="Имя пользователя">
                         {% if reg_form.username.errors %}
                            <div class="invalid-feedback">
                                {{ reg_form.username.errors|striptags }}
                            </div>
                        {% endif %}
                     </div>
                     <div class="input-group mb-3">
                         <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                         <input type="email" name="email" class="form-control" placeholder="Email">
                         {% if reg_form.email.errors %}
                            <div class="invalid-feedback">
                                {{ reg_form.email.errors|striptags }}
                            </div>
                        {% endif %}
                     </div>
                     <div class="input-group mb-3">
                         <span class="input-group-text"><i class="fas fa-lock"></i></span>
                         <input type="password" name="password1" class="form-control" placeholder="Пароль">
                         {% if reg_form.password1.errors %}
                            <div class="invalid-feedback">
                                {{ reg_form.password1.errors|striptags }}
                            </div>
                        {% endif %}
                     </div>
                     <div class="input-group mb-3">
                         <span class="input-group-text"><i class="fas fa-lock"></i></span>
                         <input type="password" name="password2" class="form-control" placeholder="Подтвердите пароль">
                         {% if reg_form.password2.errors %}
                            <div class="invalid-feedback">
                                {{ reg_form.password2.errors|striptags }}
                            </div>
                        {% endif %}

                     </div>

                     <button type="submit" class="send reg" name='register'>Зарегистрироваться</button>
                     <div class="button-container">
                        <button  onclick="IsTeacher()"  class="link-button" >Вы преподаватель?</button>
                     </div>
                 </form>
            </div>
        </div>
    </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

<footer>
    <div class = "wrapper">
        <p class = "title">Контакты</p>
        <div class = "textwidget">
            <p><b>Почта:</b> visualmathproject2024@gmail.com </p>
        </div>
    </div>
</footer>

</body>
</html>